	
CREATE TABLE `books` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `isbn` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `openid` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `title` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `image` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `alt` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `publisher` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `summary` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `price` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `rate` float NOT NULL,
 `tags` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `author` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,'9787559620590','oP42f4uwO825wnZd7lNzUGbQGzQk','建筑师','https://img1.doubanio.com/view/subject/l/public/s29952659.jpg','建筑师','后浪 | 北京联合出版公司','如果人生是一张建筑图纸 属于你的那栋房屋会是什么模样？ 哈维奖、艾斯纳奖、洛杉矶时报图像小说获奖作品 融叙事象征主义，色彩和视觉隐喻于一体的史诗级作品 大火过后，深陷中年危机的建筑师要如何重建他的生活？ ◎ 编辑推荐 ☆ 一次中年危机，一场自我放逐，一个“奥德赛式”的史 诗故事 阿斯泰里奥斯•波吕普是谁？他有着多种身份——从未建造过建筑的成功建筑师、博学但傲慢的教授、视角独到的美学家以及一位薄情自私的丈夫 ——但这全是过去的身份。 现在，他年过半百，成了自己前半生的影子。 然而，一个暴雨夜， 闪鸣的雷电将他带上了命运之旅。雷电引起的大火烧毁了他的公寓，也让他抛弃了早已被自己的傲慢毁掉的过去。阿斯泰里奥斯用仅剩的钱买了一张能到达的最远地方的车票。他是在放逐自己，还是在寻找救赎？ ☆ 一场视觉实验，一部艺术之书，被誉为“年度最华丽漫画” 这是一部关于风格...',198,9.4,'',' (美) 大卫·马祖凯利');
INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,'9787511377524','oP42f4uwO825wnZd7lNzUGbQGzQk','如何正确吵架','https://img3.doubanio.com/view/subject/l/public/s29962391.jpg','如何正确吵架','后浪 | 北京联合出版公司','学会有效争吵，吵出持久幸福◎编辑推荐☆ 爱情也许是不食人间烟火的童话，幸福却只能来自积极坦诚的撞击，哪有不吵架的伴侣？你们对待争吵的态度，将决定你们关系的未来。☆ 本书作者莱特夫妇对婚姻进行了30年研究，在伴侣培训项目中积累了大量实战经验。他们发现，一味回避争吵、维持表面和谐的做法，会让伴侣失去共同成长的机会，对爱情有害无益。只有学会正确的吵架方式，勇敢吵，坦诚吵，才有机会解决你们各自身上和亲密关系中存在的问题。☆ 作者将日常生活中的争吵分为15类，剖析了关于爱情和婚姻的各种常见误区，提出了帮助伴侣获得幸福的6条技巧。争吵不仅仅是具体事件引发的，它还可能反映出一方或双方未被满足的渴望、未被解决的问题以及某种需要打破的思维模式。你们要做的，正是借着吵架的机会挖掘这些意义，从而让你们不仅有相爱的激情，更懂相守的艺术。',45,7.7,'','[美] 朱迪斯·莱特 / 鲍勃·莱特');
INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,'9787305213410','oP42f4uwO825wnZd7lNzUGbQGzQk','世间万物','https://img3.doubanio.com/view/subject/l/public/s30013695.jpg','世间万物','南京大学出版社','☆ 献给孩子和恋人的睡前小书，愚蠢、疯狂、精妙☆ 充满好奇心的科普童话集，26个关于动植物、星系天体的故事☆ 科学家思维与诗人烂漫交织，唤起我们与所爱之人交流世界的渴望☆ BBC广播四台《一本好书》、美国独立书商协会、《卫报》一致推荐！▼内容简介26篇关于动植物、宇宙天体的科普童话集。它是一本关于宇宙与日常生活的书，始于畅游的鲑鱼 ，终 于璀璨的星空。书的主题，不局限于某种动物、植物或现象，从最渺小的地球居民：水母、晕厥的山羊和泰然自若的毛毛虫等地上生物，到辽远广布的天体：恒星、卫星……它探索神灵与驴子的相似性，爱与藤蔓的无情，以及爆炸的恒星与爆炸的海参……',58,9.3,'','[美]艾米·里奇(Amy Leach)');
INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,'9787559427434','oP42f4uwO825wnZd7lNzUGbQGzQk','局外人','https://img3.doubanio.com/view/subject/l/public/s30012665.jpg','局外人','江苏凤凰文艺出版社','☆ 献给孩子和恋人的睡前小书，愚蠢、疯狂、精妙☆ 充满好奇心的科普童话集，26个关于动植物、星系天体的故事☆ 科学家思维与诗人烂漫交织，唤起我们与所爱之人交流世界的渴望☆ BBC广播四台《一本好书》、美国独立书商协会、《卫报》一致推荐！▼内容简介26篇关于动植物、宇宙天体的科普童话集。它是一本关于宇宙与日常生活的书，始于畅游的鲑鱼 ，终 于璀璨的星空。书的主题，不局限于某种动物、植物或现象，从最渺小的地球居民：水母、晕厥的山羊和泰然自若的毛毛虫等地上生物，到辽远广布的天体：恒星、卫星……它探索神灵与驴子的相似性，爱与藤蔓的无情，以及爆炸的恒星与爆炸的海参……',45,9.0,'',' [法] 阿尔贝·加缪 ');
INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,'9787020139927','oP42f4uwO825wnZd7lNzUGbQGzQk','失踪的孩子','https://img1.doubanio.com/view/subject/l/public/s29799269.jpg','失踪的孩子','江苏凤凰文艺出版社','☆ 献给孩子和恋人的睡前小书，愚蠢、疯狂、精妙☆ 充满好奇心的科普童话集，26个关于动植物、星系天体的故事☆ 科学家思维与诗人烂漫交织，唤起我们与所爱之人交流世界的渴望☆ BBC广播四台《一本好书》、美国独立书商协会、《卫报》一致推荐！▼内容简介26篇关于动植物、宇宙天体的科普童话集。它是一本关于宇宙与日常生活的书，始于畅游的鲑鱼 ，终 于璀璨的星空。书的主题，不局限于某种动物、植物或现象，从最渺小的地球居民：水母、晕厥的山羊和泰然自若的毛毛虫等地上生物，到辽远广布的天体：恒星、卫星……它探索神灵与驴子的相似性，爱与藤蔓的无情，以及爆炸的恒星与爆炸的海参……',62,9.2,'','[意] 埃莱娜·费兰特');
INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,'9787508684031','oP42f4uwO825wnZd7lNzUGbQGzQk','原则','https://img3.doubanio.com/view/subject/l/public/s29643861.jpg','原则','江苏凤凰文艺出版社','☆ 献给孩子和恋人的睡前小书，愚蠢、疯狂、精妙☆ 充满好奇心的科普童话集，26个关于动植物、星系天体的故事☆ 科学家思维与诗人烂漫交织，唤起我们与所爱之人交流世界的渴望☆ BBC广播四台《一本好书》、美国独立书商协会、《卫报》一致推荐！▼内容简介26篇关于动植物、宇宙天体的科普童话集。它是一本关于宇宙与日常生活的书，始于畅游的鲑鱼 ，终 于璀璨的星空。书的主题，不局限于某种动物、植物或现象，从最渺小的地球居民：水母、晕厥的山羊和泰然自若的毛毛虫等地上生物，到辽远广布的天体：恒星、卫星……它探索神灵与驴子的相似性，爱与藤蔓的无情，以及爆炸的恒星与爆炸的海参……',98,8.4,'','[意] 埃莱娜·费兰特');
INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,' 9787532777914','oP42f4uwO825wnZd7lNzUGbQGzQk','鱼翅与花椒','https://img3.doubanio.com/view/subject/l/public/s29767895.jpg','鱼翅与花椒','江苏凤凰文艺出版社','☆ 献给孩子和恋人的睡前小书，愚蠢、疯狂、精妙☆ 充满好奇心的科普童话集，26个关于动植物、星系天体的故事☆ 科学家思维与诗人烂漫交织，唤起我们与所爱之人交流世界的渴望☆ BBC广播四台《一本好书》、美国独立书商协会、《卫报》一致推荐！▼内容简介26篇关于动植物、宇宙天体的科普童话集。它是一本关于宇宙与日常生活的书，始于畅游的鲑鱼 ，终 于璀璨的星空。书的主题，不局限于某种动物、植物或现象，从最渺小的地球居民：水母、晕厥的山羊和泰然自若的毛毛虫等地上生物，到辽远广布的天体：恒星、卫星……它探索神灵与驴子的相似性，爱与藤蔓的无情，以及爆炸的恒星与爆炸的海参……',48,8.3,'','[意] 埃莱娜·费兰特');
INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,'  9787559418371','oP42f4uwO825wnZd7lNzUGbQGzQk','遮蔽的天空','https://img3.doubanio.com/view/subject/l/public/s29840340.jpg','遮蔽的天空','江苏凤凰文艺出版社','☆ 献给孩子和恋人的睡前小书，愚蠢、疯狂、精妙☆ 充满好奇心的科普童话集，26个关于动植物、星系天体的故事☆ 科学家思维与诗人烂漫交织，唤起我们与所爱之人交流世界的渴望☆ BBC广播四台《一本好书》、美国独立书商协会、《卫报》一致推荐！▼内容简介26篇关于动植物、宇宙天体的科普童话集。它是一本关于宇宙与日常生活的书，始于畅游的鲑鱼 ，终 于璀璨的星空。书的主题，不局限于某种动物、植物或现象，从最渺小的地球居民：水母、晕厥的山羊和泰然自若的毛毛虫等地上生物，到辽远广布的天体：恒星、卫星……它探索神灵与驴子的相似性，爱与藤蔓的无情，以及爆炸的恒星与爆炸的海参……',49,7.9,'','[意] 埃莱娜·费兰特');
INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,'  9787559625984','oP42f4uwO825wnZd7lNzUGbQGzQk','梦的化石','https://img1.doubanio.com/view/subject/l/public/s29888548.jpg','梦的化石','江苏凤凰文艺出版社','☆ 献给孩子和恋人的睡前小书，愚蠢、疯狂、精妙☆ 充满好奇心的科普童话集，26个关于动植物、星系天体的故事☆ 科学家思维与诗人烂漫交织，唤起我们与所爱之人交流世界的渴望☆ BBC广播四台《一本好书》、美国独立书商协会、《卫报》一致推荐！▼内容简介26篇关于动植物、宇宙天体的科普童话集。它是一本关于宇宙与日常生活的书，始于畅游的鲑鱼 ，终 于璀璨的星空。书的主题，不局限于某种动物、植物或现象，从最渺小的地球居民：水母、晕厥的山羊和泰然自若的毛毛虫等地上生物，到辽远广布的天体：恒星、卫星……它探索神灵与驴子的相似性，爱与藤蔓的无情，以及爆炸的恒星与爆炸的海参……',108,8.2,'','[意] 埃莱娜·费兰特');
INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,'  9787542664051','oP42f4uwO825wnZd7lNzUGbQGzQk','冬泳','https://img3.doubanio.com/view/subject/l/public/s29902192.jpg','冬泳','江苏凤凰文艺出版社','☆ 献给孩子和恋人的睡前小书，愚蠢、疯狂、精妙☆ 充满好奇心的科普童话集，26个关于动植物、星系天体的故事☆ 科学家思维与诗人烂漫交织，唤起我们与所爱之人交流世界的渴望☆ BBC广播四台《一本好书》、美国独立书商协会、《卫报》一致推荐！▼内容简介26篇关于动植物、宇宙天体的科普童话集。它是一本关于宇宙与日常生活的书，始于畅游的鲑鱼 ，终 于璀璨的星空。书的主题，不局限于某种动物、植物或现象，从最渺小的地球居民：水母、晕厥的山羊和泰然自若的毛毛虫等地上生物，到辽远广布的天体：恒星、卫星……它探索神灵与驴子的相似性，爱与藤蔓的无情，以及爆炸的恒星与爆炸的海参……',49,8.3,'','[意] 埃莱娜·费兰特');
INSERT INTO `books`(`id`, `isbn`, `openid`, `title`, `image`, `alt`, `publisher`, `summary`, `price`, `rate`, `tags`, `author`) VALUES (NULL,'  9787533954116','oP42f4uwO825wnZd7lNzUGbQGzQk','回答不了','https://img3.doubanio.com/view/subject/l/public/s29890136.jpg','回答不了','江苏凤凰文艺出版社','☆ 献给孩子和恋人的睡前小书，愚蠢、疯狂、精妙☆ 充满好奇心的科普童话集，26个关于动植物、星系天体的故事☆ 科学家思维与诗人烂漫交织，唤起我们与所爱之人交流世界的渴望☆ BBC广播四台《一本好书》、美国独立书商协会、《卫报》一致推荐！▼内容简介26篇关于动植物、宇宙天体的科普童话集。它是一本关于宇宙与日常生活的书，始于畅游的鲑鱼 ，终 于璀璨的星空。书的主题，不局限于某种动物、植物或现象，从最渺小的地球居民：水母、晕厥的山羊和泰然自若的毛毛虫等地上生物，到辽远广布的天体：恒星、卫星……它探索神灵与驴子的相似性，爱与藤蔓的无情，以及爆炸的恒星与爆炸的海参……',59,8.5,'','[意] 埃莱娜·费兰特');
